### ISSUE TITLE
Update view contact popup to use blessing steps icons shown in design

### ISSUE THREAD

**Issue by anjosh** [Djeisen642/htm-project#16]
Design is here: https://docs.google.com/document/d/19L_tGJLrdKk5WL-B8l7905ybEo52rvcs72pPYUpLdP8/edit#heading=h.v8ga5yu9g9xm

This will need us to import fontawesome in our project. unless we can find better icons in the material icons.

**Comment by anjosh** [comment]
@Djeisen642 I spent a while trying to import fontawesome icons into the project but couldn't get it to work. I would appreciate your help if you could take a stab.

**Comment by anjosh** [comment]
this is part of the work needed for #13

**Comment by Djeisen642** [comment]
Ok.

**Comment by anjosh** [comment]
@Djeisen642 could you hold off on adding these icons to the view contact popup for now since I'm making some small updates to that at the moment.

**Comment by Djeisen642** [comment]
Yeah. No problem.  
To add fontawesome icons, use `fa-<icon name>`.

**Comment by anjosh** [comment]
Added icons to personProfile so going to say that this is done.
