### ISSUE TITLE
How to distinguish a non-user from a user?

### ISSUE THREAD

**Issue by Djeisen642** [Djeisen642/htm-project#2]
Should the invitationDate be the thing that defines a user?

**Comment by Djeisen642** [comment]
Should the password be the thing that defines a user?

**Comment by anjosh** [comment]
I think that starting off we can just have password be the thing since invitations will take more effort to implement.

**Comment by anjosh** [comment]
https://github.com/anjosh/htm-project-backend/issues/1

**Comment by anjosh** [comment]
Using the user table
