### ISSUE TITLE
Blank page at http://testhtm.herokuapp.com/

### ISSUE THREAD

**Issue by leightonpd** [Djeisen642/htm-project#4]
When loading the login page at http://testhtm.herokuapp.com/, the page doesn't display.

When loading the login page at https://testhtm.herokuapp.com/ (TLS/SSL encrypted), the page displays properly. 

I recommend that http://testhtm.herokuapp.com/ be set up to automatically redirect to https://testhtm.herokuapp.com/.

I am curious why nothing shows without the TLS/SSL encryption. Default to prevent password from being sent unencrypted?

**Comment by Djeisen642** [comment]
This looks fixed
