### ISSUE TITLE
Import csv or xlsx

### ISSUE THREAD

**Issue by Djeisen642** [Djeisen642/htm-project#6]
Needs to be able to map headers to columns and bulk import any number of guests

**Comment by anjosh** [comment]
This is the file that is on the heavenlytribe.org website and many tribal messiahs are already using. We want to be able to import this one. https://drive.google.com/file/d/0B_uVEsYLmMO6VEJJa08xb2M0Zl9pMmNnb0lRRE55aWozdHRZ/view?usp=sharing

**Comment by anjosh** [comment]
completed by #7
